### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by TheTechromancer** [requests-cache/requests-cache#781] opened 2023-02-06 16:16 UTC
I recently ran into this error in version `0.9.8`, which I was able to produce pretty reliably with the following code (against the local `python -m http.server`):

```python
from requests_cache import CachedSession
from requests_cache.backends import SQLiteCache
from concurrent.futures import ThreadPoolExecutor, as_completed

backend = SQLiteCache(db_path="/tmp/wat.sqlite", fast_save=True)
session = CachedSession(expire_after=1, backend=backend)

def cache_get():
    return session.get("http://127.0.0.1:8000")

futures = []
with ThreadPoolExecutor(max_workers=100) as e:
    for i in range(10000):
        future = e.submit(cache_get)
        futures.append(future)

for future in as_completed(futures):
    print(future.result())

```

This will yield one of two errors, either `sqlite3.OperationalError: database is locked`:
```python
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/requests_cache/session.py", line 212, in _resend
  File "/home/user/.local/lib/python3.10/site-packages/requests_cache/session.py", line 193, in _send_and_cache
  File "/home/user/.local/lib/python3.10/site-packages/requests_cache/backends/base.py", line 103, in save_response
  File "/home/user/.local/lib/python3.10/site-packages/requests_cache/backends/sqlite.py", line 268, in __setitem__
  File "/home/user/.local/lib/python3.10/site-packages/requests_cache/backends/sqlite.py", line 220, in __setitem__
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/test.py", line 18, in <module>
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
  File "/home/user/test.py", line 9, in cache_get
  File "/home/user/.local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
  File "/home/user/.local/lib/python3.10/site-packages/requests_cache/session.py", line 115, in request
  File "/home/user/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
  File "/home/user/.local/lib/python3.10/site-packages/requests_cache/session.py", line 151, in send
  File "/home/user/.local/lib/python3.10/site-packages/requests_cache/session.py", line 214, in _resend
  File "/home/user/.local/lib/python3.10/site-packages/requests_cache/backends/base.py", line 176, in delete
  File "/home/user/.local/lib/python3.10/site-packages/requests_cache/backends/sqlite.py", line 247, in bulk_delete
sqlite3.OperationalError: database is locked
```

or `sqlite3.OperationalError: unable to open database file`:
```python
Traceback (most recent call last):
  File "/home/user/test.py", line 18, in <module>
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
  File "/home/user/test.py", line 9, in cache_get
  File "/home/user/.local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
  File "/home/user/.local/lib/python3.10/site-packages/requests_cache/session.py", line 115, in request
  File "/home/user/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
  File "/home/user/.local/lib/python3.10/site-packages/requests_cache/session.py", line 141, in send
  File "/home/user/.local/lib/python3.10/site-packages/requests_cache/backends/base.py", line 80, in get_response
  File "/usr/lib/python3.10/_collections_abc.py", line 824, in get
  File "/home/user/.local/lib/python3.10/site-packages/requests_cache/backends/sqlite.py", line 271, in __getitem__
  File "/home/user/.local/lib/python3.10/site-packages/requests_cache/backends/sqlite.py", line 211, in __getitem__
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
  File "/home/user/.local/lib/python3.10/site-packages/requests_cache/backends/sqlite.py", line 168, in connection
sqlite3.OperationalError: unable to open database file
```

**Comment by JWCook** [comment] 2023-02-06 17:05
At 10000 threads, you are definitely going to need a different backend. It's briefly mentioned in the docs [here](https://requests-cache.readthedocs.io/en/stable/modules/requests_cache.backends.sqlite.html) and in SQLite's docs [here]( https://sqlite.org/whentouse.html) (under "Situations Where A Client/Server RDBMS May Work Better") that it's not suited for a high level of concurrency. I can't find any exact numbers on a maximum amount of threads, but based on some tests it seems to consistently work with 1000 threads, and starts to fail somewhere between there and 1500.

I think requests-cache's SQLite backend already has all the thread-safety measures it needs, but another pair of eyes on it would always help!

**Comment by JWCook** [comment] 2023-02-06 17:08
Oh, I see your first traceback includes `bulk_delete()`. That's more likely to be something fixable. Could you give me an example that reproduces that?

**Comment by TheTechromancer** [comment] 2023-02-06 17:41
> Oh, I see your first traceback includes `bulk_delete()`. That's more likely to be something fixable. Could you give me an example that reproduces that?

The first traceback was generated by the above code block. Sometimes it generates the second error instead, so you may need to run it a few times before it triggers.

> At 10000 threads, you are definitely going to need a different backend. 
My application only has 25 threads. The error `sqlite3.OperationalError: database is locked` appears only once in a blue moon. So the code block is only an extreme example intended to coax it out a bit quicker :)

**Comment by JWCook** [comment] 2023-02-06 17:54
Okay, if you've seen that with only 25 threads, then there must be a problem. Thanks for clarifying. I'm a bit busy this week, but I'll plan on digging into this some more next week. I have some ideas about the first error, but the second one is trickier. 

Meanwhile, could you try out the latest beta release (`1.0.0b1`) in your application? There is a chance that the first error (`database is locked`) could be partially fixed or occur less frequently.

**Comment by TheTechromancer** [comment] 2023-02-06 18:06
Much appreciated! I'll start testing with the newer version.

> I have some ideas about the first error, but the second one is trickier.

I don't think we need to worry about the second error because it's probably only indicating that we've hit the maximum number of open files, because of all the threads.

**Comment by TheTechromancer** [comment] 2023-02-14 19:35
This bug appears to be present  in `save_response()` in addition to `bulk_delete()`:
```python
  File "/root/.cache/pypoetry/virtualenvs/bbot-aKeTQkGo-py3.9/lib/python3.9/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/bbot-aKeTQkGo-py3.9/lib/python3.9/site-packages/requests_cache/session.py", line 115, in request
    return super().request(method, url, *args, **kwargs)
  File "/usr/lib/python3.9/functools.py", line 387, in _method
    return self.func(cls_or_self, *self.args, *args, **keywords)
  File "/root/.cache/pypoetry/virtualenvs/bbot-aKeTQkGo-py3.9/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.cache/pypoetry/virtualenvs/bbot-aKeTQkGo-py3.9/lib/python3.9/site-packages/requests_cache/session.py", line 147, in send
    response = self._send_and_cache(request, actions, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/bbot-aKeTQkGo-py3.9/lib/python3.9/site-packages/requests_cache/session.py", line 193, in _send_and_cache
    self.cache.save_response(response, actions.cache_key, actions.expires)
  File "/root/.cache/pypoetry/virtualenvs/bbot-aKeTQkGo-py3.9/lib/python3.9/site-packages/requests_cache/backends/base.py", line 103, in save_response
    self.responses[cache_key] = cached_response
  File "/root/.cache/pypoetry/virtualenvs/bbot-aKeTQkGo-py3.9/lib/python3.9/site-packages/requests_cache/backends/sqlite.py", line 268, in __setitem__
    super().__setitem__(key, serialized_value)
  File "/root/.cache/pypoetry/virtualenvs/bbot-aKeTQkGo-py3.9/lib/python3.9/site-packages/requests_cache/backends/sqlite.py", line 220, in __setitem__
    con.execute(
sqlite3.OperationalError: database is locked
```

**Comment by JWCook** [comment] 2023-02-18 23:40
I spent a bit of time looking into this, but still haven't found the root cause.

Two workarounds that seem to fix this:
* Increase the [lock timeout](https://docs.python.org/3/library/sqlite3.html#sqlite3.connect) (for example, `SQLiteCache(..., timeout=10)`). That's something you can change on your end without waiting for any changes in requests-cache, so I'd recommend trying that, at least temporarily.
* Update `__setitem__()` to acquire a threading lock before writing each response

Neither of those things _should_ be necessary, though. There could be some other underlying cause, like something that makes a write operation occasionally take much longer than usual, exceeding than the default lock timeout of 5 seconds. For comparison, most writes take around 1-2ms depending on response size and disk speed.

I suspect the short expiration time (`expire_after=1`) is partly responsible, or at least exposes an issue that would otherwise be quite rare. This makes it much more likely that two threads are going to try to refresh the same stale response at the same time, as in:
```
thread_1 cache read
thread_2 cache read
thread_1 request
thread_2 request
thread_1 cache write
thread_2 cache write
```

That shouldn't be a problem, though; SQLite can handle concurrent writes even on the same row, it just queues them internally. 

My next thought was that maybe there's deadlock situation, like thread 1 reader is waiting on thread 2 writer, and thread 2 reader is waiting on thread 1 writer. I don't think that's currently possible, though. If that were the case, adjusting the timeout would have no effect, and [WAL mode](https://sqlite.org/wal.html) would fix the issue, which it doesn't.

So I still have more digging to do, but at least ruled out some the most common/basic types of concurrency problems.

**Comment by JWCook** [comment] 2023-03-01 00:13
The root cause here may be that concurrent writes are only thread-safe if made from the same connection object. I'm having trouble finding documentation that clarifies that.

#240 introduced using a separate connection for each thread. I thought that was enough, but I can reproduce this error with concurrent writes, using a minimal example with just the stdlib `sqlite3` module:
```python
import sqlite3
from concurrent.futures import ThreadPoolExecutor, as_completed

with sqlite3.connect('test.db') as con:
    con.execute(f'CREATE TABLE IF NOT EXISTS test (key TEXT PRIMARY KEY)')
    con.commit()

def write():
    with sqlite3.connect('test.db') as con:
        con.execute('INSERT OR REPLACE INTO test VALUES (?)', ('key',))

futures = []
with ThreadPoolExecutor(max_workers=100) as executor:
    for i in range(1000):
        futures.append(executor.submit(write))

for future in as_completed(futures):
    future.result()
```

Using a shared connection object may not have the same problem, but adds another problem of threads clobbering each other's transactions (which, IIRC, is the main thing #240 fixed).

Also, this may also behave differently depending on what [threading mode](https://sqlite.org/threadsafe.html) your SQLite binary was compiled with. This can be checked on the command line with:
```
sqlite3 "" "SELECT * FROM pragma_compile_options WHERE compile_options LIKE 'THREADSAFE%'"
```

Completely fixing this in requests-cache will likely require using either locks or queues. Fortunately, I remembered I previously did some benchmarks with and without using a lock for each write operation, and the the performance difference was negligible (a few microseconds).

**Comment by JWCook** [comment] 2023-03-01 01:49
I believe this is now fixed in main, and after running some more benchmarks there doesn't appear to be any reduction in write performance. Your example now works, even with `timeout=0` and `max_workers=1000`. There were already automated tests for multithreading and multiprocessing, but I added some more to test for high volumes of concurrent writes.

I would still appreciate anyone's suggestions if there are more ways to improve this, though.

**Comment by TheTechromancer** [comment] 2023-03-01 02:39
Bravo, @JWCook thanks for your work on this 🙏

**Comment by JWCook** [comment] 2023-03-01 03:02
You're very welcome! I'll go ahead and close this, but let me know if you run into any other problems.

**Closed by JWCook** 2023-03-01 03:02 UTC
Labels: bug, performance

**Comment by lazka** [comment] 2023-05-08 07:09
I'm getting random deadlocks now and 

```
    self.redirects[self.create_key(r.request)] = cache_key
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/python3.11/site-packages/requests_cache/backends/sqlite.py", line 283, in __setitem__
    con.execute(
sqlite3.OperationalError: database is locked
```

:(

**Comment by lazka** [comment] 2023-05-08 07:39
I've created a reproducer: https://github.com/requests-cache/requests-cache/issues/820
