### ISSUE TITLE
The documentation on RedisCache API is misleading

### ISSUE THREAD

**Issue by samuelwang48** [requests-cache/requests-cache#669] opened 2022-07-28 02:14 UTC
### The problem
The documentation in https://requests-cache.readthedocs.io/en/stable/modules/requests_cache.backends.redis.html
says to use `host=` and `port=` to pass in a Redis connection but it may not be correct.

### Expected behavior
The doc should reflect the implementation
```
connection = redis.Redis(host='192.168.1.63', port=9876)
backend = requests_cache.RedisCache(connection=connection)
```

### Steps to reproduce the behavior
The documentation in https://requests-cache.readthedocs.io/en/stable/modules/requests_cache.backends.redis.html
says to use `host=` and `port=` to pass in a Redis connection
```
backend = RedisCache(host='192.168.1.63', port=6379)
```
However the code in https://github.com/requests-cache/requests-cache/blob/v0.9.5/requests_cache/backends/redis.py#L50
says otherwise

The reason why it was working is because redis-py in https://github.com/redis/redis-py/blob/master/redis/connection.py#L508
offered some convenience in assuming host and port are defaulted to `localhost` and `6379`

A redis-py design covered this issue.

### Workarounds
```
connection = redis.Redis(host='192.168.1.63', port=9876)
backend = requests_cache.RedisCache(connection=connection)
```

### Environment
- requests-cache version: 0.9.3, 0.9.4, 0.9.5
- Python version: 3.x
- Platform: all

**Comment by JWCook** [comment] 2022-07-28 02:30
You can pass either a `Redis` object or any [keyword args for `Redis`](https://redis-py.readthedocs.io/en/stable/connections.html#redis.Redis), including `host` and `port`. Those are passed along via `**kwargs` and any valid ones are split out via inspection and passed to a new `StrictRedis` instance. I just tested the examples in the docs with a Redis instance on an alternate port and they still work.

Do you have an example where one of those keyword args isn't working as expected?

**Comment by samuelwang48** [comment] 2022-07-28 02:39
I found this issue when I was working in a Kubernetes minikube.
When being outside minikube, everything works fine because my Redis listening on default host and port and it conveniently covered the issue.

When the process is trying to access my Redis service within minikube, my service host and port are different.
No matter how I changed it would not work and the error message contains `localhost` and `6379`. That made me wonder if it was hardcoded somewhere and I traced back to redis-py and came to this conclusion.

```
# this won't work because they are not default host and port in redis-py lib
backend = RedisCache(host='192.168.1.63', port=6379)
```

**Comment by JWCook** [comment] 2022-07-28 02:47
What does the following snippet output for you?
```python
from requests_cache import RedisCache
backend = RedisCache(host='192.168.1.63', port=9876)
print(backend.responses.connection)
```

**Comment by samuelwang48** [comment] 2022-07-28 02:49
I always got `Error 99 connecting to localhost:6379. Cannot assign requested address` inside minikube where Redis service doesn't listen on localhost and 6379.

**Comment by samuelwang48** [comment] 2022-07-28 02:54
Stacktrace
```
redis.exceptions.ConnectionError: Error 99 connecting to localhost:9954. Cannot assign requested address.

  File "/usr/local/python/lib/python3.8/site-packages/requests_cache/patcher.py", line 51, in __init__
    super().__init__(
  File "/usr/local/python/lib/python3.8/site-packages/requests_cache/session.py", line 60, in __init__
    self.cache = init_backend(cache_name, backend, **kwargs)
  File "/usr/local/python/lib/python3.8/site-packages/requests_cache/backends/__init__.py", line 76, in init_backend
    logger.debug(f'Initializing backend: {backend} {cache_name}')
  File "/usr/local/python/lib/python3.8/site-packages/requests_cache/backends/base.py", line 235, in __str__
    return f'Total rows: {len(self.responses)} responses, {len(self.redirects)} redirects'
  File "/usr/local/python/lib/python3.8/site-packages/requests_cache/backends/redis.py", line 108, in __len__
    return len(list(self.keys()))
  File "/usr/local/python/lib/python3.8/site-packages/requests_cache/backends/redis.py", line 121, in keys
    for key in self.connection.keys(f'{self.namespace}:*')
  File "/usr/local/python/lib/python3.8/site-packages/redis/commands/core.py", line 1850, in keys
    return self.execute_command("KEYS", pattern, **kwargs)
  File "/usr/local/python/lib/python3.8/site-packages/redis/client.py", line 1235, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/python/lib/python3.8/site-packages/redis/connection.py", line 1387, in get_connection
    connection.connect()
  File "/usr/local/python/lib/python3.8/site-packages/redis/connection.py", line 617, in connect
    raise ConnectionError(self._error_message(e))
```

**Comment by samuelwang48** [comment] 2022-07-28 02:55
> 

This particular one is quiet. Please look at my stacktrace for more information. Luckily I still have a copy of it.

**Comment by JWCook** [comment] 2022-07-28 03:15
Ah! That is indeed a bug, but a bit different from what I was expecting. Ironically the cause is this debug log statement:
```python
logger.debug(f'Initializing backend: {backend} {cache_name}')
```
Which I think was intended for when a backend is referenced by name (like `CachedSession(backend='redis')`). In this case `backend` is an object, and it also happens that the `__str__()` method for that object will attempt to print out the size of the cache. Except by that point the cache hasn't been initialized yet so the call will fail. Or something like that.

I believe this has been fixed in main, and those `__str__()` methods no longer make any backend calls. I will look into backporting that change for 0.9.

> This particular one is quiet.

What does that `print` statement show? You should see the redis connection object along with the host and port it's using, which should tell you whether those keyword arguments are working correctly or not. Something like:
```python
Redis<ConnectionPool<Connection<host=192.168.1.63,port=9876,db=0>>>
```

**Comment by samuelwang48** [comment] 2022-07-28 03:26
```
Redis<ConnectionPool<Connection<host=192.168.1.63,port=9876,db=0>>>
```
Yes something like this. No error presents.

**Comment by JWCook** [comment] 2022-07-30 22:28
Can you try the latest pre-release build (`pip install -U --pre requests-cache`) and let me know if that behaves any differently for you on minikube?

**Comment by samuelwang48** [comment] 2022-07-30 23:06
When I pulled it shows version "1.0.0a1" and it is working. I no longer see the error of hardcoded hostname and port.
Thank you for the fix!

**Comment by JWCook** [comment] 2022-07-30 23:16
Great! I will also backport that to 0.9 at some point, but since there's a workaround it's probably not urgent.

Let me know if you run into any other problems.

**Closed by JWCook** 2022-07-30 23:16 UTC
Labels: bug
