### ISSUE TITLE
A request with Vary response headers fails to match when it has redirects

### ISSUE THREAD

**Issue by dokempf** [requests-cache/requests-cache#809] opened 2023-03-29 12:12 UTC
Hey, thanks for this library! On the surface, it looks exactly what I am looking for, but I do not get things to work the way I intend. In my use case I want to build a requests cache and then possibly relocate that cache to a different machine that does not have access to the internet. Requests made from my library code should then be served from the cache. My minimum example (using `pytest_socket` to disable network connections) looks like this:

```python
import pytest_socket
import requests_cache
import subprocess

# Create session and use it
session = requests_cache.CachedSession("reqtest", backend="filesystem", serializer="json")
session.get("https://doi.org/10.5281/zenodo.4924875")

# Copy the cache directory to a new directory
subprocess.run(f"cp -r reqtest reqtest2".split())

# Use the copy as the cache for a new OFFLINE session
pytest_socket.disable_socket()
session2 = requests_cache.CachedSession("reqtest2", backend="filesystem", serializer="json")
print(session2.get("https://doi.org/10.5281/zenodo.4924875").url)
```

This does not work as intended - `session2` does not work with the cache built by `session`. Am I doing something wrong? Is this even a supported use case? Looking forward to any feedback.

**Comment by JWCook** [comment] 2023-03-30 23:39
Yes, you can relocate the cache.

Something else is going on with your example request that's odd, though. The cached response isn't being used because it's failing to match according to the `Vary` header that the server is sending. I also notice there's a redirect in there (doi.org -> zenodo.org), and each request has a different `Vary` value.

So this could be a bug in how requests-cache is handling `Vary` with redirects. I'll look into it some more and get back to you.

**Comment by JWCook** [comment] 2023-06-02 19:36
Sorry for the delay on this. I have confirmed that this is specifically an issue with handling `Vary` with redirects. It happens with or without relocating cache files, for example:
```python
from requests_cache import CachedSession
import logging

logging.basicConfig(level=logging.DEBUG)

session = CachedSession("vary_test")
r = session.get("https://doi.org/10.5281/zenodo.4924875")
print(r.from_cache, r.cache_key)

r = session.get("https://doi.org/10.5281/zenodo.4924875")
print(r.from_cache, r.cache_key)
```

`Failed Vary check` will show up in the logs, and with some more debugging I can see that it's comparing the `doi.org` request against the `zenodo.org` request.

I'll make a fix for this soon. Right now I'm just struggling to find any authoritative documentation on expected behavior in this case. If I can't find anything, I will update this to always compare using the last request in the redirect chain, if available (in this case the `zenodo.org` request).

**Comment by dokempf** [comment] 2023-06-02 19:40
Thanks for the heads-up, much appreciated. I have put the feature development relying on this on ice until it is resolved, but will happily continue once it is resolved.

**Comment by JWCook** [comment] 2023-06-05 22:51
Fixes for this are in main, and the example above now works as expected.

This will be included in the next patch release, probably within a couple weeks.

**Closed** 2023-06-05 22:50 UTC
Labels: bug, question
