### ISSUE TITLE
bson has no attribute 'dumps', pymongo 4.5 error

### ISSUE THREAD

**Issue by tomsabe** [requests-cache/requests-cache#877] opened 2023-09-10 11:34 UTC
Received the error below when using requests-cache==1.1.0 and pymongo==4.5.0, macOS Ventura. The error is resolved if I use pymongo==4.4.1.

Traceback:
File "<usersfile>.py", line 6, in <module>
    from requests_cache import CachedSession
  File "/usr/local/lib/python3.9/dist-packages/requests_cache/__init__.py", line 7, in <module>
    from .backends import *
  File "/usr/local/lib/python3.9/dist-packages/requests_cache/backends/__init__.py", line 7, in <module>
    from .base import BaseCache, BaseStorage, DictStorage
  File "/usr/local/lib/python3.9/dist-packages/requests_cache/backends/base.py", line 22, in <module>
    from ..serializers import SerializerType, init_serializer
  File "/usr/local/lib/python3.9/dist-packages/requests_cache/serializers/__init__.py", line 26, in <module>
    from .preconf import (
  File "/usr/local/lib/python3.9/dist-packages/requests_cache/serializers/preconf.py", line 95, in <module>
    [bson_preconf_stage, Stage(bson, **_get_bson_functions())],
  File "/usr/local/lib/python3.9/dist-packages/requests_cache/serializers/pipeline.py", line 29, in __init__
    self.dumps = getattr(obj, dumps) if isinstance(dumps, str) else dumps
AttributeError: module 'bson' has no attribute 'dumps'

**Comment by JWCook** [comment] 2023-09-11 18:39
Thanks for the heads up. I'll get that fixed.

**Comment by JWCook** [comment] 2023-09-19 21:31
Hmm, I can't seem to reproduce this locally or in CI. When pymongo is installed (any version), it appears to correctly use [bson.encode()](https://pymongo.readthedocs.io/en/stable/api/bson/index.html#bson.BSON.encode) and decode(). I haven't tested on macOS, but a platform-specific seems unlikely.

Your traceback mentions `bson.dumps()`, which is supposed to only be used if:
* the bson serializer is used
* pymongo isn't installed
* the standalone [bson package](https://github.com/py-bson/bson) is installed (which uses "dumps/loads" instead of "encode/decode")

In the environment that reproduces this bug, could you please show me the output of:
```sh
pip freeze
```
and:
```sh
python -c "import bson; print(bson.__file__)"
```

**Comment by JWCook** [comment] 2023-09-19 21:39
Here's something else to try: locally checkout the changes from [this branch](https://github.com/requests-cache/requests-cache/tree/bson). That will test whether the `AttributeError` you're getting is hiding some other error that's indirectly causing this.

**Comment by JWCook** [comment] 2024-01-08 20:35
I'll close this since I can't reproduce it, but let me know if you try the steps listed above.

**Closed by JWCook** 2024-01-08 20:35 UTC
Labels: bug, cant-reproduce
