### ISSUE TITLE
TypeError: can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by jpavlav** [requests-cache/requests-cache#973] opened 2024-03-14 19:32 UTC
### The problem
Periodically (I think when the cache is needing to be refreshed) I am seeing the following error:

```TypeError: can't compare offset-naive and offset-aware datetimes```

### Expected behavior
Ultimately, I would expect the cache to be refreshed without error.

### Steps to reproduce the behavior
I wish I had a specific example of this but I don't at the moment. In order to resolve this, I've been manually removing the `sqlite` files that I believe are the culprit. Hopefully, when it happens again, I can hop into the virtual environment where the package is installed and throw some `breakpoint()`'s in to figure out what is actually happening. If I do, I'll probably submit a PR to address this.

### Workarounds
The only workaround I am aware of at this time is to remove the `sqlite` file associated with the stale cache that is breaking things.

### Environment
- requests-cache version: 1.2.0
- Python version: 3.8.10
- Platform: Ubuntu - Focal

**Comment by JWCook** [comment] 2024-03-14 19:40
Are you by chance accessing the same cache from multiple virtual environments running different versions of requests-cache? In v1.2, for compatibility with python 3.12, stored timestamps were switched from timezone-naive to timezone-aware (#864).

It's also possible that could come up after upgrading to v1.2, if there were previously cached responses that are otherwise still valid. I thought that was already accounted for, but either way you're right, in this case it would be better to quietly fail and fetch a new response.

**Comment by jpavlav** [comment] 2024-03-15 01:57
You're probably right. There are multiple virtualenvs running. I thought I'd gone through and updated `requests-cache` in all of them (shame on me for not updating the tool that uses `requests-cache` as a dependency itself). But perhaps I haven't. Either way, I'll wait and see if it happens again. If it does, I can probably debug and kick up a PR to silently fail and grab a new cache.

That is of course unless you beat me to it 😄 . I'd guess you know the code paths much better than I do offhand.

**Comment by jpavlav** [comment] 2024-04-03 18:27
Finally hit that bug again and I did have one virtual environment left that was running `1.1.0` and I think that was the culprit.

**Comment by JWCook** [comment] 2024-04-03 21:03
Good to know! Thanks for following up.

**Comment by theOehrly** [comment] 2024-07-28 13:06
@JWCook I don't think that the silent failure for this has been implemented since? 
I (or rather users of a tool that I am maintaining) are running into this problem somewhat frequently.
I'm open to creating a PR for this if there is interest in getting this fixed/implemented.

**Comment by JWCook** [comment] 2024-07-31 21:51
@theOehrly I probably closed this because OP's issue was resolved, and in general using a single cache with multiple versions of requests-cache at the same time isn't supported. I went ahead and made changes for this in `main`, though.

To make sure we're talking about the same thing, could you post a complete traceback? And do you know if users are encountering this for some reason other than the cases mentioned above?

**Comment by theOehrly** [comment] 2024-08-01 09:03
@JWCook that was a quick response and fix now. I hadn't really looked into this in more detail because I wanted to quickly ask before I do that, in case I'm missing something obvious. I just did a more thorough investigation, though.

It seems like it is actually not possible to trigger this problem by just upgrading to a newer version of requests-cache. 
In v1.2.0 the following code was added as well: 
https://github.com/requests-cache/requests-cache/blob/be5f7fe4a83d37429453371f7afaa1beba200b50/requests_cache/policy/expiration.py#L74-L80
This already takes care of the old responses by adding the UTC timezone info. Therefore, I am unable to reproduce the problem on >=1.2.0 if I access a response that was cached with an earlier version.

The error only seems to occur when going the other way round. That is, creating a cached response with requests-cache>=1.2.0 and then accessing it again with an earlier version. Obviously, there is no reasonable way to fix this. At least not one that I can think of.
For reference, the full traceback for that would be
<details>

```
Traceback (most recent call last):
  File "C:\Dateien\Code\Formula1\FastF1\FastF1\exp_test.py", line 8, in <module>
    seasons = ergast.get_seasons()
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Dateien\Code\Formula1\FastF1\FastF1\src\fastf1\ergast\interface.py", line 653, in get_seasons
    return self._build_default_result(endpoint='seasons',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dateien\Code\Formula1\FastF1\FastF1\src\fastf1\ergast\interface.py", line 591, in _build_default_result
    return self._build_result(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Dateien\Code\Formula1\FastF1\FastF1\src\fastf1\ergast\interface.py", line 530, in _build_result
    resp = cls._get(url, params)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dateien\Code\Formula1\FastF1\FastF1\src\fastf1\ergast\interface.py", line 491, in _get
    r = Cache.requests_get(url, headers=HEADERS, params=params,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dateien\Code\Formula1\FastF1\FastF1\src\fastf1\req.py", line 299, in requests_get
    return cls._requests_session_cached.get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dateien\Code\Formula1\FastF1\FastF1\venvs\venv312\Lib\site-packages\requests_cache\session.py", line 103, in get
    return self.request('GET', url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dateien\Code\Formula1\FastF1\FastF1\venvs\venv312\Lib\site-packages\requests_cache\session.py", line 159, in request
    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dateien\Code\Formula1\FastF1\FastF1\venvs\venv312\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dateien\Code\Formula1\FastF1\FastF1\venvs\venv312\Lib\site-packages\requests_cache\session.py", line 195, in send
    actions.update_from_cached_response(cached_response, self.cache.create_key, **kwargs)
  File "C:\Dateien\Code\Formula1\FastF1\FastF1\venvs\venv312\Lib\site-packages\requests_cache\policy\actions.py", line 184, in update_from_cached_response
    usable_response = self.is_usable(cached_response)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dateien\Code\Formula1\FastF1\FastF1\venvs\venv312\Lib\site-packages\requests_cache\policy\actions.py", line 152, in is_usable
    or (cached_response.is_expired and self._stale_while_revalidate is True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dateien\Code\Formula1\FastF1\FastF1\venvs\venv312\Lib\site-packages\requests_cache\models\response.py", line 149, in is_expired
    return self.expires is not None and datetime.utcnow() >= self.expires
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can't compare offset-naive and offset-aware datetimes
```

</details>

Testing was done with the default sqlite backend, if that is relevant.

As far as I know, this only occurred when sharing the cache over multiple virtual environments or when reinstalling another Python version. The project where this was reported a few times configures a default cache directory if users don't explicitly set a different cache directory. But that means, multiple venvs will default to using the same cache. So it makes sense that this problem can occur.

In the end, I don't think the change you added was really necessary. Sorry for the confusion and misunderstanding here.

**Comment by JWCook** [comment] 2024-08-13 18:34
No problem! Feel free to reach out if you run into any other issues.

**Closed by JWCook** 2024-08-13 18:34 UTC
Labels: bug
