### ISSUE TITLE
Doesn't work in Github Workflows/Actions

### ISSUE THREAD

**Issue by Arthavruksha** [requests-cache/requests-cache#663] opened 2022-07-15 17:49 UTC
### The problem
So when i run Requests_Cache in my Local Machine an .sqlite file is automatically formed and caching is started directly as all requests are added in that .sqlite file. Although when i run the same code in Github Workflows/Actions this .sqlite file isn't formed even though i have defined (backend='sqlite') in the Code and thus caching doesn't happen

### Expected behavior
_I expected that a .sqlite file should get formed in the Repository and Caching should start happening

### Steps to reproduce the behavior
Here's the code from my actual python file
`session = requests_cache.CachedSession('demo_cache',use_cache_dir=True,backend='sqlite')`

And here's my .yml file code that runs in Github Workflows/Actions
`name: Corporate Announcements

on:
  schedule:
    - cron: '0 * * * *' # 

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          cache: 'pip'
          cache-dependency-path: 'ca-requirements.txt'
          
      - name: install python packages
        run: pip install -r ca-requirements.txt
          
      - name: execute py script
        run: python announcementsv2.py`

### Workarounds
I am not aware of 

### Environment
- requests-cache version: (Latest Version)
- Python version: ( `3.9`)
- Platform: Github workflows

**Comment by JWCook** [comment] 2022-07-15 17:58
I see. `use_cache_dir=True` may be the problem there. In a GitHub Actions runner, you may not have access to create new directories in `~/.cache`. For any files you create/modify in a workflow, it's best to keep them in the CI project directory.

Try this and see if that helps:
```python
session = requests_cache.CachedSession('demo_cache', backend='sqlite')
```

That should create a `demo_cache.sqlite` file in the current directory. And I believe you could also use `actions/cache` to persist that across multiple workflows, if you wanted (although I haven't tested that myself).

**Comment by Arthavruksha** [comment] 2022-07-15 18:00
Will try this

**Comment by Arthavruksha** [comment] 2022-07-16 05:30
Hi this method also isn't working . What should I do now ?

**Comment by Arthavruksha** [comment] 2022-07-16 06:39
Well this also doesn't work , what should I do now ?

**Comment by Arthavruksha** [comment] 2022-07-16 16:38
Yo @JWCook Any solutions u found on this topic ?

**Comment by JWCook** [comment] 2022-07-19 23:56
I just tested requests-cache with GitHub actions, and I wasn't able to reproduce any problems. I added some [example config here](https://github.com/requests-cache/requests-cache/blob/main/examples/github_actions.yml) that runs [this example script](https://github.com/requests-cache/requests-cache/blob/main/examples/basic_sessions.py) and stores the `.sqlite` file for future workflow runs.

So I don't have enough information to tell what the problem is. It could be something within that `announcementsv2.py` file. Try [enabling debug logs](https://requests-cache.readthedocs.io/en/stable/user_guide/troubleshooting.html#logging) and see if that provides any useful info.

**Comment by Arthavruksha** [comment] 2022-07-20 01:20
Okay Will check it out today and let you know

**Comment by Arthavruksha1** [comment] 2022-07-20 15:36
Hi JWCook this is my another account, Its still not creating any file at my end

Why are u running the python script 2 times in .yml file ?

This is my updated .yml file

```
name: Corporate Announcements

on:
  schedule:
    - cron: '0 * * * *' # 

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - id: cache
        uses: actions/cache@v3
        with:
         path: demo_cache.sqlite
         key: none

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          cache: 'pip'
          cache-dependency-path: 'ca-requirements.txt'
          
      - name: install python packages
        run: pip install -r ca-requirements.txt
          
      - name: execute py script
        run: python announcementsv2.py`
```

And u were asking that `announcementsv2.py` might have some error. This is the part of the .py script which has requests in it 

`def smeca():   
    print("Started Pulling")
    currentd = date.today()
    s = requests_cache.CachedSession('demo_cache', backend='sqlite')
    headers =   {'Host':'www.nseindia.com','User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0','Accept':'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Accept-Language':'en-US,en;q=0.5', 'Accept-Encoding':'gzip, deflate, br','DNT':'1', 'Connection':'keep-alive', 'Upgrade-Insecure-Requests':'1','Pragma':'no-cache','Cache-Control':'no-cache',  }
    url = 'https://www.nseindia.com/'
    step = s.get(url,headers=headers)`

And after that the code ends. Is their anything i am doing wrong

**Comment by JWCook** [comment] 2022-07-20 16:04
And did you enable debug logs? That will tell you when headers or other settings disable caching for a request.

**Comment by Arthavruksha1** [comment] 2022-07-20 16:44
Removed  'Cache-Control':'no-cache' from code sir although still nothing is happening , Will try with enabling debug logs

**Comment by Arthavruksha1** [comment] 2022-07-20 17:33
Hey JWCook i have figured out the way to scrape it without the header parameter . Will test it out tommorrow

**Comment by Arthavruksha1** [comment] 2022-07-22 06:29
And this is how my .yml file looks like . Do let me know if this has something which is preventing caching

```
name: Corporate Announcements

on:
  schedule:
    - cron: '0 * * * *' # 

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - id: cache
        uses: actions/cache@v3
        with:
         path: demo_cache.sqlite
         key: none

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          cache: 'pip'
          cache-dependency-path: 'ca-requirements.txt'
          
      - name: install python packages
        run: pip install -r ca-requirements.txt
          
      - name: execute py script
        run: python announcementsv2.py
```

**Comment by Arthavruksha1** [comment] 2022-07-22 12:11
Hi JWCook

In this scrip their is another instance where i have used request_cache . This is the code for it 

```
def getdata(constraints):
    session = requests_cache.CachedSession('demo_cache', backend='sqlite')
    API_KEY = 'xyz'
    base_url = 'xyz'
    headers = {"api_token": API_KEY}
    payload = {"constraints": json.dumps(constraints)}
    response = session.get(base_url, headers = headers, params=payload)     
    print(response.url)
    df = response.json()['response']['results']
    df = pd.DataFrame(df)
    return df
```

**Comment by Arthavruksha1** [comment] 2022-07-23 12:22
And i checked out this directory although it didn't contain `example_cache.sqlite` file as u had said

https://github.com/requests-cache/requests-cache/tree/main/examples

**Comment by Arthavruksha1** [comment] 2022-07-23 12:42
Hi JWCook it worked finally it has created an demo_cache file .

Although this is only for that virtual machine run , I want more of an permanent solution than creating an demo_cache file for every run it should instead add a single file to repository and add all cache their .

Is their any way to do that ?

![image](https://user-images.githubusercontent.com/106299072/180605331-b4320856-97bf-474d-b049-27ae153c4611.png)

**Comment by JWCook** [comment] 2022-07-23 15:40
> it should instead add a single file to repository

In the original issue description, when you said the sqlite file wasn't being created, you mean it wasn't being committed back to your git repo? That's not something GitHub Actions does automatically for you. If that's what you want, there are some actions that can help with that, for example [github-push-action](https://github.com/ad-m/github-push-action) and [add-and-commit](https://github.com/EndBug/add-and-commit).

If you haven't done it already, first test that the file is actually getting created on the github runner. Add something like this to your workflow file after running your python script:
```yml
- run: ls -al
- run: test -f demo_cache.sqlite && echo 'Cache file created' || echo 'Cache file missing'
```

**Comment by Arthavruksha1** [comment] 2022-07-24 08:51
> In the original issue description, when you said the sqlite file wasn't being created, you mean it wasn't being committed back to your git repo? 

Yeah that's what i wanted

**Comment by Arthavruksha1** [comment] 2022-07-25 13:11
Hi JWCook did u read my above message ?

**Comment by JWCook** [comment] 2022-07-25 16:01
Your questions are about how to use GitHub Actions, so you can either look at [github-push-action](https://github.com/ad-m/github-push-action), or ask for help on the [GitHub Community Forum](https://github.community/c/code-to-cloud/github-actions).

**Closed by JWCook** 2022-07-25 16:01 UTC
Labels: bug, cant-reproduce
